name: dependent-base

library:
  source-dirs: src

default-extensions:
- ApplicativeDo
- DataKinds
- GADTs
- PolyKinds
- StandaloneDeriving
- TypeOperators
- TypeFamilies

dependencies:
- base >= 4.7 && < 5

